# Generated by Django 5.1 on 2024-09-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bblog', '0004_remove_post_live_remove_post_thumbnail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='big_category',
            new_name='bigCategory',
        ),
    ]
