# Generated by Django 5.1 on 2024-09-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bblog', '0005_rename_big_category_post_bigcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='card_text',
            field=models.CharField(default='', max_length=255, verbose_name='記事説明文'),
        ),
    ]
