# Generated by Django 5.1 on 2024-09-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bblog', '0006_alter_post_card_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='card_text',
            field=models.TextField(default='', verbose_name='記事説明文'),
        ),
    ]
