version: '3'

services:

  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - '../blog:/code'
    ports:
      - "8000:8000"
    depends_on:
      - db
    container_name: docker_blog
    tty: true
    working_dir: '/code'

  db:
    image: postgres
    volumes:
        - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "my_blog"
      POSTGRES_HOST_AUTH_METHOD: "trust"


  pgadmin4:
    image: dpage/pgadmin4
    ports:
        - 8888:80
    volumes:
        - pgadmin4_data:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db


volumes:
    postgres_data:
    pgadmin4_data: