# Generated by Django 2.2.9 on 2020-02-26 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='公開可能か'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='A28WZDTYEY.jpg', upload_to='media', verbose_name='サムネイル'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 2, 26, 17, 20, 18, 437716)),
        ),
    ]
