# Generated by Django 2.2.9 on 2020-02-26 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0002_auto_20200226_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 2, 26, 17, 29, 45, 279457)),
        ),
    ]
