# Generated by Django 2.2.9 on 2020-02-28 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0003_auto_20200226_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 2, 28, 16, 18, 44, 208443)),
        ),
    ]
