# Generated by Django 2.2.9 on 2020-03-04 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0005_auto_20200228_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 5, 3, 41, 28, 307671)),
        ),
    ]
